### PR TITLE
Fix three_primeness math

### LINKED ISSUE #71: three_primeness math
The `-d` parameter filters by the location of the insertion within the gene.

Here is the current relevant code in `process_mapping.py`

```
if strand == "+":
    three_primeness = (nucleotide - start) / (end - start)
if strand == "-":
    three_primeness = (end - nucleotide) / (end - start)
```

**First problem**: denominator should be the length of the gene (i.e., 1 more than the current calculation). Suggested solution:

```
if strand == "+":
    three_primeness = (nucleotide - start) / length
else:
    three_primeness = (end - nucleotide) / length
```

**Second problem**: See example below for a transposon insertion at the 4th bp of a 9 bp gene:

```
+ strand gene:

5'-ATGTACTAG
      ^

^ first nt in the TA site

```
Current math = ((3 + start) - start) / 9 = 3/9. However, this should be 4/9, so need to add 1.

What about - strand genes? Note this is the same sequence just flipped to the other strand.

```
- strand gene:
5'-CTAGTACAT    (gene starts over here)
       ^
```

Current math = ((end - (end - 4) / 9) = 4/9. If we look at the sample gene and count *from the 5' end* (i.e., the reverse complement of the ATG on the right side), then it should be 5/9. However, for the sake of biology, we want insertions in the same position to be called the same way whether the gene is on the + or - strand. Therefore, I think that 4/9 is the right call here.

Proposal is for the insertion nucleotide to continue to represent the first position of a TA site (i.e., lowest genome coordinate) regardless of what direction the gene(s) are.

```
5'-TA
3'-AT
   ^
Always call the "first" nucleotide regardless of gene annotations.
```

However, when we are processing the site data to collect gene-level data, we will use the nt in the TA site that is closest to the 5' end of the gene.

```
+ strand gene:
5'-ATGTACTAG
      ^
      *

- strand gene:
5'-CTAGTACAT
       ^*

^ = site-level insertion point
* = gene-level three-primeness call
```

Therefore... proposed solution:

```
if strand == "+":
    three_primeness = (1 + nucleotide - start) / length
else:
    three_primeness = (end - nucleotide) / length
```

### PR DESCRIPTION
**Pull request by mandel01**

### CODE REVIEW

**Comment by mandel01** [comment]
@eburgoswisc This is passing on my local machine but failing on TravisCI. I probably won't be able to dig into this until tomorrow evening.

**Comment by eburgoswisc** [comment]
Fixed!

**Comment by mandel01** [comment]
Great... but why did that work? What changed on your commit? The values look identical.

**Comment by eburgoswisc** [comment]
Im not sure. I just reran the test dataset and then pushed the new gene files which were causing the fail on Travis. The values do look identical, maybe there is a subtle change somewhere that we cannot see? Python can definitely be mysterious sometimes...

**Comment by mandel01** [comment]
Ok, I see the whitespace differences in Atom:
screenshot 2019-02-17 20 24 22

I couldn't see them in Pycharm and I'm a bit confused as to why they appeared in the first place.
screenshot 2019-02-17 20 24 12

**Comment by eburgoswisc** [comment]
Interesting. Somehow pushing the files from pycharm changed whitespace characters? Its the only point in the workflow where a change like that could happen because files were generated with pyinseq.

**Comment by mandel01** [comment]
Seems related to this: https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

**Comment by mandel01** [comment]
Here were my current settings. Seems like I may want `false` instead of `input`

```
$ git config core.autocrlf
input
```

**Comment by eburgoswisc** [comment]
Yep definitely. I remember I had to change mine too in the config and also in the IDE. Pycharm I think has it system dependent so it should be good if you are on Mac, I would check to make sure.

**Comment by eburgoswisc** [comment]
Would make sense to leave it on if we were Windows developers. This might come into play when we make Pyinseq functional in Windows.

**Pull request merged**
