### PR TITLE
Nfifty Implementation

### PR DESCRIPTION
**Pull request by eburgoswisc**

### CODE REVIEW

**Comment by mandel01** [comment]
Is there a reason that the following files are included in the commit?

```
pyinseq/third-party/bowtie-1.1.1-mac/bowtie-buildc
pyinseq/tests/data/output_demultiplex/log.txt
pyinseq/tests/data/output_demultiplex_notrim/log.txt
pyinseq/tests/data/output_genomeprep/log.txt
pyinseq/tests/data/output_pyinseq/E001_01_bowtie.txt
pyinseq/tests/data/output_pyinseq/E001_02_bowtie.txt
```

**Comment by eburgoswisc** [comment]
The log.txt modification was to include the nfifty result so that it passes pytests. I do not know why the bowtie files are different, however after visual inspection, the reads are still the same just on different lines. This may have to do with bowtie somehow doing things a bit different on my mac, but the sites and gene files have not change. Buildc file however is exclusive to my machine, I will make a last commit to remove this.

**Comment by mandel01** [comment]
You need `pyinseq/tests/data/output_pyinseq/log.txt` but not the other log files right?

**Comment by mandel01** [comment]
I would also remove the changes to the bowtie files. See if it passes the tests. It's better to have narrower commits that aren't cluttered.

**Pull request merged**
