### PR TITLE
Adding progress bar to demultiplex functions

### PR DESCRIPTION
**Pull request by eburgoswisc**
This pull request will be for adding a progress bar to the demultiplex functions of pyinseq, one of the heavy performance task. It will contain bars for demultiplexing fastq and writing trimmed/not-trimmed reads to fastq files. In addition, a CustomStream class was added to allow the logging class to use tqdm writing module so that log messages do not overlap with progress bars.

### CODE REVIEW

**Comment by eburgoswisc** [comment]
Travis is throwing a fail for "make test". This is internally cause by pytest not properly tearing down after test_genome_script function. I do not know why this is happening. I will look into it this week.

**Comment by mandel01** [comment]
Let's discuss briefly this afternoon.

**Comment by eburgoswisc** [comment]
Passed TravisCI. If code looks good, go ahead and squash/merge.

**Comment by mandel01** [comment]
@eburgoswisc Have you tried this with large input files (100-200 M reads), or with .gzipped input files?

Here is what I get when I run it. When I run our simple test it completes (and the status bars look awesome!)

```
(pyinseq) DMI-MBPro2-mandel:pyinseq markmandel$ pyinseq -i pyinseq/tests/data/input/example01.fastq -s pyinseq/tests/data/input/example01.txt -g pyinseq/tests/data/input/ES114v2.gb -e TEST_TQDM3
2019-03-13 16:17 - INFO - runner - Process command line arguments
2019-03-13 16:17 - INFO - utils - Make directory: results/TEST_TQDM3
2019-03-13 16:17 - INFO - utils - Make directory: results/TEST_TQDM3/raw_data/
2019-03-13 16:17 - INFO - utils - Make directory: results/TEST_TQDM3/genome_lookup/
2019-03-13 16:17 - INFO - runner - Demultiplex reads
Demultiplexing Reads: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 534/534 [00:00<00:00, 61118.77reads/s]
2019-03-13 16:17 - INFO - demultiplex - Writing reads to E001_01.fastq
Writing E001_01 reads: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 252/252 [00:00<00:00, 167003.41reads/s]
2019-03-13 16:17 - INFO - demultiplex - Writing reads to E001_02.fastq
Writing E001_02 reads: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 274/274 [00:00<00:00, 234634.40reads/s]
2019-03-13 16:17 - INFO - demultiplex - Writing reads to _other.fastq
Writing _other reads: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 15040.09reads/s]
2019-03-13 16:17 - INFO - demultiplex - Writing trimmed reads to E001_01.fastq
Writing E001_01 trimmed reads: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 252/252 [00:00<00:00, 80127.71reads/s]
2019-03-13 16:17 - INFO - demultiplex - Writing trimmed reads to E001_02.fastq
Writing E001_02 trimmed reads: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 274/274 [00:00<00:00, 66665.08reads/s]
2019-03-13 16:17 - INFO - demultiplex - Total records demultiplexed: 534
2019-03-13 16:17 - INFO - runner - Prepare genome features (.ftt) and fasta nucleotide (.fna) files
  Nucleotide file output file: results/TEST_TQDM3/genome_lookup/genome.fna
  Feature table output file: results/TEST_TQDM3/genome_lookup/genome.ftt
2019-03-13 16:17 - INFO - runner - Prepare bowtie index
2019-03-13 16:17 - INFO - runner - Building bowtie index files in results/TEST_TQDM3/genome_lookup
2019-03-13 16:17 - INFO - runner - Map with bowtie
2019-03-13 16:17 - INFO - runner - Sample E001_01: map reads with bowtie
2019-03-13 16:17 - INFO - runner - # reads processed: 252
# reads with at least one reported alignment: 252 (100.00%)
# reads that failed to align: 0 (0.00%)
Reported 252 alignments to 1 output stream(s)

2019-03-13 16:17 - INFO - runner - Sample E001_01: summarize the site data from the bowtie results
2019-03-13 16:17 - INFO - runner - Sample E001_01: map site data to genes
2019-03-13 16:17 - INFO - runner - T50 result for E001_01: 3
2019-03-13 16:17 - INFO - runner - Sample E001_02: map reads with bowtie
2019-03-13 16:17 - INFO - runner - # reads processed: 274
# reads with at least one reported alignment: 274 (100.00%)
# reads that failed to align: 0 (0.00%)
Reported 274 alignments to 1 output stream(s)

2019-03-13 16:17 - INFO - runner - Sample E001_02: summarize the site data from the bowtie results
2019-03-13 16:17 - INFO - runner - Sample E001_02: map site data to genes
2019-03-13 16:17 - INFO - runner - T50 result for E001_02: 3
2019-03-13 16:17 - INFO - runner - Aggregate gene mapping from all samples into the summary_data_table
2019-03-13 16:17 - INFO - runner - T50 E001_01: 3
2019-03-13 16:17 - INFO - runner - T50 E001_02: 3
2019-03-13 16:17 - INFO - runner - Print samples info: results/TEST_TQDM3/samples.yml
2019-03-13 16:17 - INFO - runner - Print summary log: results/TEST_TQDM3/log.txt
2019-03-13 16:17 - INFO - runner - Print command entered
pyinseq -i pyinseq/tests/data/input/example01.fastq -s pyinseq/tests/data/input/example01.txt -g pyinseq/tests/data/input/ES114v2.gb -e TEST_TQDM3
2019-03-13 16:17 - INFO - runner - Print settings
command: pyinseq
experiment: TEST_TQDM3
path: results/TEST_TQDM3/
parse_genbank_file: True
genome_path: results/TEST_TQDM3/genome_lookup/
organism: genome
raw_path: results/TEST_TQDM3/raw_data/
generate_bowtie_index: True
process_reads: True
process_sample_list: True
map_to_genome: True
samples_yaml: results/TEST_TQDM3/samples.yml
summary_log: results/TEST_TQDM3/log.txt
write_trimmed_reads: True
summary_table: results/TEST_TQDM3/summary_gene_table.txt
min_counts: 3
max_ratio: 10
keep_all: False
barcode_length: 4
disruption: 1.0
2019-03-13 16:17 - INFO - runner - Print samples detail
E001_01:
  barcode: GAAG
E001_02:
  barcode: CTTT

2019-03-13 16:17 - INFO - runner - ***** pyinseq complete! *****
```

When I try with a gzipped file it yields an error. We need to add a test for this.

```
(pyinseq) DMI-MBPro2-mandel:pyinseq markmandel$ pyinseq -i ~/src/pyinseq/private/example02.fastq.gz -s pyinseq/tests/data/input/example02.txt -g pyinseq/tests/data/input/ES114v2.gb -e TEST_TQDM4
2019-03-13 16:19 - INFO - runner - Process command line arguments
2019-03-13 16:19 - INFO - utils - Make directory: results/TEST_TQDM4
2019-03-13 16:19 - INFO - utils - Make directory: results/TEST_TQDM4/raw_data/
2019-03-13 16:19 - INFO - utils - Make directory: results/TEST_TQDM4/genome_lookup/
2019-03-13 16:19 - INFO - runner - Demultiplex reads
Traceback (most recent call last):
  File "/Users/markmandel/anaconda3/envs/pyinseq/bin/pyinseq", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/markmandel/Dropbox/repos/pyinseq/scripts/pyinseq", line 7, in <module>
    runner.main(args)
  File "/Users/markmandel/Dropbox/repos/pyinseq/pyinseq/runner.py", line 434, in main
    demultiplex_fastq(reads, samples_dict, settings)
  File "/Users/markmandel/Dropbox/repos/pyinseq/pyinseq/demultiplex.py", line 53, in demultiplex_fastq
    results = fastq_generator(reads)
  File "/Users/markmandel/Dropbox/repos/pyinseq/pyinseq/utils.py", line 104, in fastq_generator
    for i in screed.fastq.fastq_iter(mmap.mmap(f.fileno(), 0, prot=mmap.PROT_READ)):
  File "/Users/markmandel/anaconda3/envs/pyinseq/lib/python3.6/site-packages/screed/fastq.py", line 21, in fastq_iter
    line = to_str(line.strip())
  File "/Users/markmandel/anaconda3/envs/pyinseq/lib/python3.6/site-packages/screed/utils.py", line 6, in to_str
    line = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

When I first gunzip the file, the program then hangs on the `Demultiplex Reads` step. It's been here for 20 minutes with no status bar or update.

```
(pyinseq) DMI-MBPro2-mandel:pyinseq markmandel$ pyinseq -i ~/src/pyinseq/private/example02.fastq -s pyinseq/tests/data/input/example02.txt -g pyinseq/tests/data/input/ES114v2.gb -e TEST_TQDM5
2019-03-13 16:20 - INFO - runner - Process command line arguments
2019-03-13 16:20 - INFO - utils - Make directory: results/TEST_TQDM5
2019-03-13 16:20 - INFO - utils - Make directory: results/TEST_TQDM5/raw_data/
2019-03-13 16:20 - INFO - utils - Make directory: results/TEST_TQDM5/genome_lookup/
2019-03-13 16:20 - INFO - runner - Demultiplex reads

```

**Comment by mandel01** [comment]
Small other point I noticed when looking at the output... this section:

```
2019-03-13 16:17 - INFO - demultiplex - Writing reads to E001_01.fastq
2019-03-13 16:17 - INFO - demultiplex - Writing reads to E001_02.fastq
2019-03-13 16:17 - INFO - demultiplex - Writing reads to _other.fastq
2019-03-13 16:17 - INFO - demultiplex - Writing trimmed reads to E001_01.fastq
2019-03-13 16:17 - INFO - demultiplex - Writing trimmed reads to E001_02.fastq
```
should probably be:
```
2019-03-13 16:17 - INFO - demultiplex - Writing reads to raw_data/E001_01.fastq
2019-03-13 16:17 - INFO - demultiplex - Writing reads to raw_data/E001_02.fastq
2019-03-13 16:17 - INFO - demultiplex - Writing reads to raw_data/_other.fastq
2019-03-13 16:17 - INFO - demultiplex - Writing trimmed reads to E001_01_trimmed.fastq
2019-03-13 16:17 - INFO - demultiplex - Writing trimmed reads to E001_02_trimmed.fastq
```

**Comment by eburgoswisc** [comment]
I will look into it tomorrow afternoon. To handle bigger files and gzipped, I will move to using ScreedDB class to open them and process the reads (with progress bar). However, the progress bar is handled for de-multiplex. Ill also add tests.

**Comment by mandel01** [comment]
Sounds good. Here are couple of things to consider:

1. Is mmap required for the tqdm function? If not, then consider making this PR just about tqdm, and then add mmap later if desired. This would make it easier to evaluate and merge the tqdm PR, and also easier to troubleshoot if behavior changes in the future.

2. You mentioned that you made some changes due to speed. I think we should wait to optimize until we are a bit further along, then set up some standard benchmarks for this. For example in this case, it may work much faster on smaller data sets but flail on larger ones.

**Comment by eburgoswisc** [comment]
Can you do squash/merge? I'll make a separate pull request for adding new fastq.gz test files and methods, unless its ideal to keep committing to this one.

**Comment by mandel01** [comment]
Hi @eburgoswisc, great to have this. Please make the following changes:
- The current implementation is very confusing for the user. We don't want progress bars for each of the buffered reads. See the screenshot below. The demultiplexing is only 5% done but the user will think it is complete. I think the benefit of the progress bar is that you can hide those other details in the background. tqdm takes care of the number of reads, how many are demultiplex, and how long the remaining portion is predicted to take. Once the progress bar makes it to 100% then all of the demultiplexing should be done.
- Change the log entry of "Counting sequences in input for progress bar" to "Preparing to demultiplex reads."
- Remove the .gitignore and VSCode files from the commit. Try to manage these on your local machine for now. If needed we can add a bunch of stuff to the .gitignore in a future commit.

Screenshot 2019-04-05 13 05 02

**Comment by eburgoswisc** [comment]
Should I remove the logger.info that is called in the writing methods too? I can leave that message in the progress bar and it will not show in the log.txt. The trimmed reads bar will disappear.
screenshot

**Pull request merged**
